# Generated by Django 3.2.6 on 2025-05-09 13:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="We'll want to be able to group subscriptions based on the category they belong to", max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a company that supplies a subscription service', max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a Subscription', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the subscription', max_length=1000, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='cost of a subscription', max_digits=5)),
                ('yearlysavings', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Savings percentage when taking a subscription for 12 months', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('luxury', models.BooleanField(default=True, help_text='Is this a luxury subscription?')),
                ('category', models.ForeignKey(default=1, help_text='Category of the subscription', on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.category')),
                ('company', models.ForeignKey(help_text='Parent company of the subscription', null=True, on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.company')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular subscription - which will be owned by a user', primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, help_text='Start date of the subscription', null=True)),
                ('duration', models.DurationField(blank=True, help_text='Duration of the subscription', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End Date of the subscription', null=True)),
                ('country', django_countries.fields.CountryField(default='BE', max_length=2)),
                ('sub_username', models.CharField(blank=True, max_length=1024, null=True)),
                ('sub_password', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Active'), ('d', 'Disabled'), ('p', 'Planned to start'), ('e', 'Planned to end')], default='d', help_text='Subscription active, inactive or planned to start, or planned to end', max_length=1)),
                ('subowner', models.ForeignKey(blank=True, help_text='The user that owns this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(help_text='The subscription that this instance is for', null=True, on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['end_date'],
                'permissions': (('Do not renew', 'Set subscription to not be renewed at end date'),),
            },
        ),
        migrations.CreateModel(
            name='SubsaverUser',
            fields=[
                ('subsaver_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user', primary_key=True, serialize=False)),
                ('subsaver_username', models.CharField(blank=True, max_length=1024)),
                ('subsaver_password', models.CharField(blank=True, max_length=1024)),
                ('subsaver_email', models.EmailField(blank=True, max_length=1024)),
                ('subsaver_country', django_countries.fields.CountryField(default='BE', max_length=2)),
                ('subsaver_subscription', models.ManyToManyField(help_text='Subscriptions that this user has', to='subscriptions.SubscriptionInstance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subsaver_username'],
                'permissions': (('Can add subscription', 'Can add a subscription to the user'),),
            },
        ),
    ]
